import Head from 'next/head'
import { Box, Flex, Heading, Tab, TabList, TabPanel, TabPanels, Tabs } from "@chakra-ui/react"
import Footer from '../components/Footer';
import CasesToday from '../components/CasesToday';

export default function Home() {
  return (
    <>
      <Head>
        <title>MY Covid Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box h="calc(100vh - var(--chakra-sizes-footer))">
        <Flex direction="column" alignItems="center" minH="full" minW="90vw">
          <Tabs isFitted variant="enclosed" w="full">
            <TabList>
              <Tab>Cases Today</Tab>
              <Tab>Second</Tab>
              <Tab>Third</Tab>
            </TabList>
            <TabPanels>
              <TabPanel>
                <CasesToday />
              </TabPanel>
              <TabPanel>
                  Coming soon #1!
              </TabPanel>
              <TabPanel>
                Coming soon #2!
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Flex>
        <Footer/>
      </Box>
    </>
  );
}
