import Head from 'next/head'
import Image from 'next/image'
import SpikeMap from '../components/SpikeMap';
import useEpidemicData from '../lib/useEpidemicData';
import styles from '../styles/Home.module.css';

export default function Home() {
  const {
    casesMalaysiaLoading,
    casesMalaysiaData,
    casesStateLoading,
    casesStateData,
    clustersLoading,
    clustersData,
    deathsMalaysiaLoading,
    deathsMalaysiaData,
    deathsStateLoading,
    deathsStateData,
    hospitalLoading,
    hospitalData,
    icuLoading,
    icuData,
    pkrcLoading,
    pkrcData,
    testsMalaysiaLoading,
    testsMalaysiaData,
  } = useEpidemicData();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Cases Today</h1>
        <p>
          {!casesMalaysiaLoading &&
            casesMalaysiaData &&
            casesMalaysiaData[casesMalaysiaData.length - 1].cases_new}
        </p>
        <SpikeMap data={casesStateData} loading={casesStateLoading} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
